directories:
  output: dist
  buildResources: build
appId: reborncraftlauncher
productName: RebornCraft Launcher
artifactName: '${productName}-${version}.${ext}'
copyright: Copyright © 2021 Alp Eren Vural
win:
  target:
    - target: nsis
      arch: x64
nsis:
  oneClick: false
  perMachine: false
  allowElevation: true
  allowToChangeInstallationDirectory: true
mac:
  target: dmg
  category: public.app-category.games
linux:
  target: AppImage
  maintainer: Daniel Scalzi
  vendor: Daniel Scalzi
  synopsis: Modded Minecraft Launcher
  description: 'Custom launcher which allows users to join modded servers. All mods, configurations, and updates are handled automatically.'
  category: Game
compression: maximum
files:
  - filter:
      - '!{dist,.gitignore,.vscode,docs,dev-app-update.yml,.travis.yml,.nvmrc,.eslintrc.json,build.js}'
extraResources:
  - filter:
      - libraries
asar: true
electronVersion: 9.0.0
